// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyManagement.Data;

#nullable disable

namespace PharmacyManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114104557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "مسکن",
                            CreatedAt = new DateTime(2025, 11, 14, 15, 15, 56, 759, DateTimeKind.Local).AddTicks(5179),
                            Description = "مسکن و تب‌بر",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "داروسازی سبحان",
                            Name = "پاراستامول",
                            Price = 5000m,
                            ProductionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2025, 11, 14, 15, 15, 56, 759, DateTimeKind.Local).AddTicks(5180)
                        },
                        new
                        {
                            Id = 2,
                            Category = "آنتی بیوتیک",
                            CreatedAt = new DateTime(2025, 11, 14, 15, 15, 56, 759, DateTimeKind.Local).AddTicks(5185),
                            Description = "آنتی بیوتیک",
                            ExpiryDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "داروسازی کیمیدارو",
                            Name = "آموکسی سیلین",
                            Price = 15000m,
                            ProductionDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2025, 11, 14, 15, 15, 56, 759, DateTimeKind.Local).AddTicks(5185)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
